name: frmv
description: Form Validator
version: 0.0.1
repository: https://github.com/huanguan1978/frmv

topics:
  - form
  - validation
  - validator
  - validation-form

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  formz: ^0.7.0
  intl: any
  intl_translation: any
  string_validator: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
